set nocompatible              " be iMproved, required
filetype off                  " required

filetype plugin indent on    " required

if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=light

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"set colorscheme
let g:gruvbox_italic=1
set t_Co=256
set background=dark

" Autoindent options
set tabstop=4
set softtabstop=4
"set noexpandtab
set expandtab
set shiftwidth=4
set autoindent
set smartindent
set cindent
set number
set nocompatible
set mouse=a
set cursorline


" Gvim settings
if has('gui_running')
	set guifont=Inconsolata\ 13
endif

" Enable save as root hack
cmap w!! w !sudo tee > /dev/null %

source ~/.vim/vim_plugins.vim

if (has("termguicolors"))
    set termguicolors
endif

" use 256 colors in terminal
if !has("gui_running")
    set t_Co=256
    set term=screen-256color
endif

" fix cursor display in cygwin
if has("win32unix")
    let &t_ti.="\e[1 q"
    let &t_SI.="\e[5 q"
    let &t_EI.="\e[1 q"
    let &t_te.="\e[0 q"
endif

set t_8b=[48;2;%lu;%lu;%lum
set t_8f=[38;2;%lu;%lu;%lum

""" Theme settings
colorscheme solarized
set background=dark
